spring:
  application:
    name: springboot_09_ssm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?userSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234