spring:
  application:
    name: springboot_08_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    # 更换Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource