spring:
  application:
    name: mybatisplus_01_quickstart
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  # 关闭SpringBoot控制台Banner
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    # 关闭MyBatisPlus控制台Banner
    banner: false